import { StyleSheet } from "react-native";
import {
  FontSizes,
  FontWeights,
  LetterSpacings,
  LineHeights,
} from "./properties";

export const textVariants = StyleSheet.create({
  // Font style normal
  // Weight Medium
  h1MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H1,
    lineHeight: LineHeights.H1,
    letterSpacing: LetterSpacings.H1,
  },
  h2MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H2,
    lineHeight: LineHeights.H2,
    letterSpacing: LetterSpacings.H2,
  },
  h3MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H3,
    lineHeight: LineHeights.H3,
    letterSpacing: LetterSpacings.H3,
  },
  h4MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H4,
    lineHeight: LineHeights.H4,
    letterSpacing: LetterSpacings.H4,
  },
  h5MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H5,
    lineHeight: LineHeights.H5,
    letterSpacing: LetterSpacings.H5,
  },
  h6MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H6,
    lineHeight: LineHeights.H6,
    letterSpacing: LetterSpacings.H6,
  },
  p1MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P1,
    lineHeight: LineHeights.P1,
    letterSpacing: LetterSpacings.P1,
  },
  p2MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P2,
    lineHeight: LineHeights.P2,
    letterSpacing: LetterSpacings.P2,
  },
  p3MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P3,
    lineHeight: LineHeights.P3,
    letterSpacing: LetterSpacings.P3,
  },
  p4MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P4,
    lineHeight: LineHeights.P4,
    letterSpacing: LetterSpacings.P4,
  },
  p5MediumNormal: {
    fontFamily: "HelveticaNeue-Medium",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P5,
    lineHeight: LineHeights.P5,
    letterSpacing: LetterSpacings.P5,
  },
  // Weight bold
  h1BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H1,
    lineHeight: LineHeights.H1,
    letterSpacing: LetterSpacings.H1,
  },
  h2BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H2,
    lineHeight: LineHeights.H2,
    letterSpacing: LetterSpacings.H2,
  },
  h3BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H3,
    lineHeight: LineHeights.H3,
    letterSpacing: LetterSpacings.H3,
  },
  h4BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H4,
    lineHeight: LineHeights.H4,
    letterSpacing: LetterSpacings.H4,
  },
  h5BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H5,
    lineHeight: LineHeights.H5,
    letterSpacing: LetterSpacings.H5,
  },
  h6BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H6,
    lineHeight: LineHeights.H6,
    letterSpacing: LetterSpacings.H6,
  },
  p1BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P1,
    lineHeight: LineHeights.P1,
    letterSpacing: LetterSpacings.P1,
  },
  p2BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P2,
    lineHeight: LineHeights.P2,
    letterSpacing: LetterSpacings.P2,
  },
  p3BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P3,
    lineHeight: LineHeights.P3,
    letterSpacing: LetterSpacings.P3,
  },
  p4BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P4,
    lineHeight: LineHeights.P4,
    letterSpacing: LetterSpacings.P4,
  },
  p5BoldNormal: {
    fontFamily: "HelveticaNeue-Bold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P5,
    lineHeight: LineHeights.P5,
    letterSpacing: LetterSpacings.P5,
  },
  // Weight Condensed bold
  h1CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H1,
    lineHeight: LineHeights.H1,
    letterSpacing: LetterSpacings.H1,
  },
  h2CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H2,
    lineHeight: LineHeights.H2,
    letterSpacing: LetterSpacings.H2,
  },
  h3CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H3,
    lineHeight: LineHeights.H3,
    letterSpacing: LetterSpacings.H3,
  },
  h4CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H4,
    lineHeight: LineHeights.H4,
    letterSpacing: LetterSpacings.H4,
  },
  h5CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H5,
    lineHeight: LineHeights.H5,
    letterSpacing: LetterSpacings.H5,
  },
  h6CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H6,
    lineHeight: LineHeights.H6,
    letterSpacing: LetterSpacings.H6,
  },
  p1CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P1,
    lineHeight: LineHeights.P1,
    letterSpacing: LetterSpacings.P1,
  },
  p2CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P2,
    lineHeight: LineHeights.P2,
    letterSpacing: LetterSpacings.P2,
  },
  p3CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P3,
    lineHeight: LineHeights.P3,
    letterSpacing: LetterSpacings.P3,
  },
  p4CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P4,
    lineHeight: LineHeights.P4,
    letterSpacing: LetterSpacings.P4,
  },
  p5CondensedBoldNormal: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P5,
    lineHeight: LineHeights.P5,
    letterSpacing: LetterSpacings.P5,
  },
  // Weight black
  h1CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H1,
    lineHeight: LineHeights.H1,
    letterSpacing: LetterSpacings.H1,
  },
  h2CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H2,
    lineHeight: LineHeights.H2,
    letterSpacing: LetterSpacings.H2,
  },
  h3CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H3,
    lineHeight: LineHeights.H3,
    letterSpacing: LetterSpacings.H3,
  },
  h4CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H4,
    lineHeight: LineHeights.H4,
    letterSpacing: LetterSpacings.H4,
  },
  h5CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H5,
    lineHeight: LineHeights.H5,
    letterSpacing: LetterSpacings.H5,
  },
  h6CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H6,
    lineHeight: LineHeights.H6,
    letterSpacing: LetterSpacings.H6,
  },
  p1CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P1,
    lineHeight: LineHeights.P1,
    letterSpacing: LetterSpacings.P1,
  },
  p2CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P2,
    lineHeight: LineHeights.P2,
    letterSpacing: LetterSpacings.P2,
  },
  p3CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P3,
    lineHeight: LineHeights.P3,
    letterSpacing: LetterSpacings.P3,
  },
  p4CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P4,
    lineHeight: LineHeights.P4,
    letterSpacing: LetterSpacings.P4,
  },
  p5CondensedBlackNormal: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P5,
    lineHeight: LineHeights.P5,
    letterSpacing: LetterSpacings.P5,
  },
  // Font style italic
  // Weight normal
  h1MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H1,
    lineHeight: LineHeights.H1,
    letterSpacing: LetterSpacings.H1,
    fontStyle: "italic",
  },
  h2MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H2,
    lineHeight: LineHeights.H2,
    letterSpacing: LetterSpacings.H2,
    fontStyle: "italic",
  },
  h3MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H3,
    lineHeight: LineHeights.H3,
    letterSpacing: LetterSpacings.H3,
    fontStyle: "italic",
  },
  h4MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H4,
    lineHeight: LineHeights.H4,
    letterSpacing: LetterSpacings.H4,
    fontStyle: "italic",
  },
  h5MediumItalic: {
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H5,
    lineHeight: LineHeights.H5,
    letterSpacing: LetterSpacings.H5,
    fontStyle: "italic",
  },
  h6MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.H6,
    lineHeight: LineHeights.H6,
    letterSpacing: LetterSpacings.H6,
    fontStyle: "italic",
  },
  p1MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P1,
    lineHeight: LineHeights.P1,
    letterSpacing: LetterSpacings.P1,
    fontStyle: "italic",
  },
  p2MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P2,
    lineHeight: LineHeights.P2,
    letterSpacing: LetterSpacings.P2,
    fontStyle: "italic",
  },
  p3MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P3,
    lineHeight: LineHeights.P3,
    letterSpacing: LetterSpacings.P3,
    fontStyle: "italic",
  },
  p4MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P4,
    lineHeight: LineHeights.P4,
    letterSpacing: LetterSpacings.P4,
    fontStyle: "italic",
  },
  p5MediumItalic: {
    fontFamily: "HelveticaNeue-MediumItalic",
    fontWeight: FontWeights.MEDIUM,
    fontSize: FontSizes.P5,
    lineHeight: LineHeights.P5,
    letterSpacing: LetterSpacings.P5,
    fontStyle: "italic",
  },
  // Weight bold
  h1BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H1,
    lineHeight: LineHeights.H1,
    letterSpacing: LetterSpacings.H1,
    fontStyle: "italic",
  },
  h2BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H2,
    lineHeight: LineHeights.H2,
    letterSpacing: LetterSpacings.H2,
    fontStyle: "italic",
  },
  h3BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H3,
    lineHeight: LineHeights.H3,
    letterSpacing: LetterSpacings.H3,
    fontStyle: "italic",
  },
  h4BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H4,
    lineHeight: LineHeights.H4,
    letterSpacing: LetterSpacings.H4,
    fontStyle: "italic",
  },
  h5BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H5,
    lineHeight: LineHeights.H5,
    letterSpacing: LetterSpacings.H5,
    fontStyle: "italic",
  },
  h6BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H6,
    lineHeight: LineHeights.H6,
    letterSpacing: LetterSpacings.H6,
    fontStyle: "italic",
  },
  p1BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P1,
    lineHeight: LineHeights.P1,
    letterSpacing: LetterSpacings.P1,
    fontStyle: "italic",
  },
  p2BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P2,
    lineHeight: LineHeights.P2,
    letterSpacing: LetterSpacings.P2,
    fontStyle: "italic",
  },
  p3BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P3,
    lineHeight: LineHeights.P3,
    letterSpacing: LetterSpacings.P3,
    fontStyle: "italic",
  },
  p4BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P4,
    lineHeight: LineHeights.P4,
    letterSpacing: LetterSpacings.P4,
    fontStyle: "italic",
  },
  p5BoldItalic: {
    fontFamily: "HelveticaNeue-BoldItalic",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P5,
    lineHeight: LineHeights.P5,
    letterSpacing: LetterSpacings.P5,
    fontStyle: "italic",
  },
  // Weight black
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  h1CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H1,
    lineHeight: LineHeights.H1,
    letterSpacing: LetterSpacings.H1,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  h2CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H2,
    lineHeight: LineHeights.H2,
    letterSpacing: LetterSpacings.H2,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  h3CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H3,
    lineHeight: LineHeights.H3,
    letterSpacing: LetterSpacings.H3,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  h4CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H4,
    lineHeight: LineHeights.H4,
    letterSpacing: LetterSpacings.H4,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  h5CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H5,
    lineHeight: LineHeights.H5,
    letterSpacing: LetterSpacings.H5,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  h6CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.H6,
    lineHeight: LineHeights.H6,
    letterSpacing: LetterSpacings.H6,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  p1CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P1,
    lineHeight: LineHeights.P1,
    letterSpacing: LetterSpacings.P1,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  p2CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P2,
    lineHeight: LineHeights.P2,
    letterSpacing: LetterSpacings.P2,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  p3CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P3,
    lineHeight: LineHeights.P3,
    letterSpacing: LetterSpacings.P3,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  p4CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P4,
    lineHeight: LineHeights.P4,
    letterSpacing: LetterSpacings.P4,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBold && Italic FontFamily is missing, so only the Bold variant is shown */
  p5CondensedBoldItalic: {
    fontFamily: "HelveticaNeue-CondensedBold",
    fontWeight: FontWeights.BOLD,
    fontSize: FontSizes.P5,
    lineHeight: LineHeights.P5,
    letterSpacing: LetterSpacings.P5,
    fontStyle: "italic",
  },
  // Weight black
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  h1CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H1,
    lineHeight: LineHeights.H1,
    letterSpacing: LetterSpacings.H1,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  h2CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H2,
    lineHeight: LineHeights.H2,
    letterSpacing: LetterSpacings.H2,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  h3CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H3,
    lineHeight: LineHeights.H3,
    letterSpacing: LetterSpacings.H3,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  h4CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H4,
    lineHeight: LineHeights.H4,
    letterSpacing: LetterSpacings.H4,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  h5CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H5,
    lineHeight: LineHeights.H5,
    letterSpacing: LetterSpacings.H5,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  h6CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.H6,
    lineHeight: LineHeights.H6,
    letterSpacing: LetterSpacings.H6,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  p1CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P1,
    lineHeight: LineHeights.P1,
    letterSpacing: LetterSpacings.P1,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  p2CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P2,
    lineHeight: LineHeights.P2,
    letterSpacing: LetterSpacings.P2,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  p3CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P3,
    lineHeight: LineHeights.P3,
    letterSpacing: LetterSpacings.P3,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  p4CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P4,
    lineHeight: LineHeights.P4,
    letterSpacing: LetterSpacings.P4,
    fontStyle: "italic",
  },
  /** @deprecated The CondensedBlack && Italic FontFamily is missing, so only the black variant is shown */
  p5CondensedBlackItalic: {
    fontFamily: "HelveticaNeue-CondensedBlack",
    fontWeight: FontWeights.BLACK,
    fontSize: FontSizes.P5,
    lineHeight: LineHeights.P5,
    letterSpacing: LetterSpacings.P5,
    fontStyle: "italic",
  },
});
